---
version: "3"
services:
 devopsdb:
   image: prudhvireddicherla/ourproject:db
   ports:
     - "3306:3306"

 application:
   image: prudhvireddicherla/ourproject:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
